// Licensed under the MIT license. See LICENSE file in the project root for full license information.

using ElasticsearchFulltextExample.Database.Model;

namespace ElasticsearchFulltextExample.Api.Infrastructure.Outbox.Consumer
{
    /// <summary>
    /// An interface for consuming a single <see cref="OutboxEvent"/>.
    /// </summary>
    public interface IOutboxEventConsumer
    {
        /// <summary>
        /// Consumes a given <see cref="OutboxEvent">.
        /// </summary>
        /// <param name="outboxEvent">Outbox Event generated by an Event Producer</param>
        /// <param name="cancellationToken">Cancellation Token to cancel downstream asynchronous calls</param>
        /// <returns>Awaitable Task</returns>
        Task ConsumeOutboxEventAsync(OutboxEvent outboxEvent, CancellationToken cancellationToken);
    }
}